# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uplink/common/pb/edgeauth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fuplink/common/pb/edgeauth.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n\x19\x45\x64geRegisterAccessRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_grant\x18\x01 \x01(\t\x12\x0e\n\x06public\x18\x02 \x01(\x08\"\x9e\x01\n\x1a\x45\x64geRegisterAccessResponse\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\x12\x12\n\nsecret_key\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x43\n\x1f\x66ree_tier_restricted_expiration\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2U\n\x08\x45\x64geAuth\x12I\n\x0eRegisterAccess\x12\x1a.EdgeRegisterAccessRequest\x1a\x1b.EdgeRegisterAccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uplink.common.pb.edgeauth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EDGEREGISTERACCESSREQUEST']._serialized_start=68
  _globals['_EDGEREGISTERACCESSREQUEST']._serialized_end=133
  _globals['_EDGEREGISTERACCESSRESPONSE']._serialized_start=136
  _globals['_EDGEREGISTERACCESSRESPONSE']._serialized_end=294
  _globals['_EDGEAUTH']._serialized_start=296
  _globals['_EDGEAUTH']._serialized_end=381
# @@protoc_insertion_point(module_scope)
