"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (C) 2026 Storj Labs, Inc.
See LICENSE for copying information.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EdgeRegisterAccessRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_GRANT_FIELD_NUMBER: builtins.int
    PUBLIC_FIELD_NUMBER: builtins.int
    access_grant: builtins.str
    public: builtins.bool
    def __init__(
        self,
        *,
        access_grant: builtins.str = ...,
        public: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["access_grant", b"access_grant", "public", b"public"]) -> None: ...

global___EdgeRegisterAccessRequest = EdgeRegisterAccessRequest

@typing_extensions.final
class EdgeRegisterAccessResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_KEY_ID_FIELD_NUMBER: builtins.int
    SECRET_KEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    FREE_TIER_RESTRICTED_EXPIRATION_FIELD_NUMBER: builtins.int
    access_key_id: builtins.str
    secret_key: builtins.str
    endpoint: builtins.str
    @property
    def free_tier_restricted_expiration(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        access_key_id: builtins.str = ...,
        secret_key: builtins.str = ...,
        endpoint: builtins.str = ...,
        free_tier_restricted_expiration: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["free_tier_restricted_expiration", b"free_tier_restricted_expiration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["access_key_id", b"access_key_id", "endpoint", b"endpoint", "free_tier_restricted_expiration", b"free_tier_restricted_expiration", "secret_key", b"secret_key"]) -> None: ...

global___EdgeRegisterAccessResponse = EdgeRegisterAccessResponse
