# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uplink/common/pb/project_info.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#uplink/common/pb/project_info.proto\x12\x08metainfo\"4\n\rRequestHeader\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\x0c\x12\x12\n\nuser_agent\x18\x02 \x01(\x0c\"=\n\x12ProjectInfoRequest\x12\'\n\x06header\x18\x0f \x01(\x0b\x32\x17.metainfo.RequestHeader\"+\n\x13ProjectInfoResponse\x12\x14\n\x0cproject_salt\x18\x01 \x01(\x0c\"O\n\x13RevokeAPIKeyRequest\x12\'\n\x06header\x18\x0f \x01(\x0b\x32\x17.metainfo.RequestHeader\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\x0c\"\x16\n\x14RevokeAPIKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uplink.common.pb.project_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTHEADER']._serialized_start=49
  _globals['_REQUESTHEADER']._serialized_end=101
  _globals['_PROJECTINFOREQUEST']._serialized_start=103
  _globals['_PROJECTINFOREQUEST']._serialized_end=164
  _globals['_PROJECTINFORESPONSE']._serialized_start=166
  _globals['_PROJECTINFORESPONSE']._serialized_end=209
  _globals['_REVOKEAPIKEYREQUEST']._serialized_start=211
  _globals['_REVOKEAPIKEYREQUEST']._serialized_end=290
  _globals['_REVOKEAPIKEYRESPONSE']._serialized_start=292
  _globals['_REVOKEAPIKEYRESPONSE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
