"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RequestHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_KEY_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    api_key: builtins.bytes
    user_agent: builtins.bytes
    def __init__(
        self,
        *,
        api_key: builtins.bytes = ...,
        user_agent: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key", b"api_key", "user_agent", b"user_agent"]) -> None: ...

global___RequestHeader = RequestHeader

@typing_extensions.final
class ProjectInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RequestHeader: ...
    def __init__(
        self,
        *,
        header: global___RequestHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header"]) -> None: ...

global___ProjectInfoRequest = ProjectInfoRequest

@typing_extensions.final
class ProjectInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_SALT_FIELD_NUMBER: builtins.int
    project_salt: builtins.bytes
    def __init__(
        self,
        *,
        project_salt: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["project_salt", b"project_salt"]) -> None: ...

global___ProjectInfoResponse = ProjectInfoResponse

@typing_extensions.final
class RevokeAPIKeyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    API_KEY_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RequestHeader: ...
    api_key: builtins.bytes
    def __init__(
        self,
        *,
        header: global___RequestHeader | None = ...,
        api_key: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key", b"api_key", "header", b"header"]) -> None: ...

global___RevokeAPIKeyRequest = RevokeAPIKeyRequest

@typing_extensions.final
class RevokeAPIKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RevokeAPIKeyResponse = RevokeAPIKeyResponse
